name: Build OpenWrt 24.10 (GL-MT6000 / Flint 2)

on:
  workflow_dispatch:        # manual trigger
  push:
    branches: [ openwrt-24.10 ]   # optional: auto-build when you push to this branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Checkout official OpenWrt branch 24.10
      - name: Checkout OpenWrt 24.10 branch
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: openwrt-24.10

      # 2️⃣  Record commit info for artifact tagging
      - name: Save commit info
        run: |
          echo "OPENWRT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "OpenWrt commit: $(git rev-parse HEAD)"

      # 3️⃣  Install build dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
          gettext git libncurses5-dev libssl-dev python3 python3-setuptools \
          rsync unzip zlib1g-dev file wget


      # 4️⃣  Update and install all package feeds
      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 5️⃣  Configure Flint 2 (GL-MT6000)
      - name: Configure Flint 2 target
        run: |
          make defconfig
          sed -i "/CONFIG_TARGET_/d" .config
          echo "CONFIG_TARGET_mediatek=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic_glinet_gl-mt6000=y" >> .config
          make defconfig

      # 6️⃣  Build firmware
      - name: Build firmware
        run: |
          make -j$(nproc) || make -j1 V=s

      # 7️⃣  Upload the resulting sysupgrade images
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-24.10-${{ env.OPENWRT_COMMIT }}-flint2
          path: bin/targets/
